name: android_time_tracker
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.4
  provider: ^5.0.0
  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0
  cloud_firestore_web: ^2.2.0
  rxdart: ^0.27.1





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  firebase_auth: ^0.14.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  assets:
    - images/google logo.png
    - images/facebook logo.png
    - images/gmail logo.png
    - images/cgoogle logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

